### ISSUE TITLE
Not being able to update to the latest Mac os Big sur

### ISSUE THREAD

**Issue by Aquibislam** [wadimw/asus-vivobook-x512fl-hackintosh#1]
First of all thanks a lot for all the help.i was wondering if you've yet upgraded to big sur cause I kind of got my Asus x512 in boot loop

**Comment by wadimw** [comment]
Hi, unfortunately I don't have this laptop anymore – last I've seen it was with Mojave. To get Big Sur to work You'll most likely need to convert to OpenCore https://dortania.github.io/OpenCore-Install-Guide/

**Comment by Aquibislam** [comment]
> Hi, unfortunately I don't have this laptop anymore – last I've seen it was with Mojave. To get Big Sur to work You'll most likely need to convert to OpenCore https://dortania.github.io/OpenCore-Install-Guide/

Hey , thanks for the suggestion i did update to Catalina with opencore but there's one problem of tgtbridge , the patches you made for making trackpad work in mojave with clover is not supported in opencore so I'm having hard time to make trackpad work . Please tell me how do i move tgtbridge to opencore so that i can use trackpad please 🙏
